# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [@doctrine.orm.entity_manager]

    app.twig.extension:
        class: AdminBundle\Service\TwigService
        tags:
            - { name: twig.extension }