-- MySQL Script generated by MySQL Workbench
-- 05/07/16 19:55:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisrec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisrec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisrec` DEFAULT CHARACTER SET utf8 ;
USE `sisrec` ;

-- -----------------------------------------------------
-- Table `sisrec`.`TB_PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisrec`.`TB_PERFIL` (
  `id_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `tp_perfil` VARCHAR(20) NOT NULL,
  `st_perfil` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisrec`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisrec`.`TB_USUARIO` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `id_perfil` INT(11) NOT NULL,
  `nm_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `observacao` VARCHAR(4000) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tp_sexo` VARCHAR(9) NOT NULL,
  `cep` VARCHAR(8) CHARACTER SET 'big5' NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `st_usuario` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_TB_USUARIO_TB_PERFIL1_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_TB_USUARIO_TB_PERFIL1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `sisrec`.`TB_PERFIL` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisrec`.`TB_TELEFONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisrec`.`TB_TELEFONE` (
  `id_telefone` INT(11) NOT NULL AUTO_INCREMENT,
  `ddd_telefone` VARCHAR(9) NOT NULL,
  `num_telefone` VARCHAR(45) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_TB_TELEFONE_TB_USUARIO1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_TB_TELEFONE_TB_USUARIO1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sisrec`.`TB_USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisrec`.`TB_TP_MATERIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisrec`.`TB_TP_MATERIAL` (
  `id_tp_material` INT(11) NOT NULL AUTO_INCREMENT,
  `tp_material` VARCHAR(100) NOT NULL,
  `st_material` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tp_material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisrec`.`TB_MATERIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisrec`.`TB_MATERIAL` (
  `id_material` INT(11) NOT NULL AUTO_INCREMENT,
  `qt_material` INT(5) NOT NULL,
  `dt_inclusao` DATE NOT NULL,
  `vl_material` DECIMAL(18,2) NOT NULL,
  `ds_material` VARCHAR(100) NOT NULL,
  `total_material` DECIMAL(18,2) NOT NULL,
  `id_tp_material` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `fk_TB_MATERIAL_TB_TP_MATERIAL1_idx` (`id_tp_material` ASC),
  INDEX `fk_TB_MATERIAL_TB_USUARIO1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_TB_MATERIAL_TB_TP_MATERIAL1`
    FOREIGN KEY (`id_tp_material`)
    REFERENCES `sisrec`.`TB_TP_MATERIAL` (`id_tp_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_MATERIAL_TB_USUARIO1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sisrec`.`TB_USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisrec`.`TB_TIPO_GASTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisrec`.`TB_TIPO_GASTO` (
  `id_tp_gasto` INT(11) NOT NULL AUTO_INCREMENT,
  `tp_gasto` VARCHAR(100) NOT NULL,
  `st_tp_gasto` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tp_gasto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisrec`.`TB_GASTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisrec`.`TB_GASTO` (
  `id_gastos` INT(11) NOT NULL AUTO_INCREMENT,
  `vl_gasto` DECIMAL(18,2) NOT NULL,
  `num_nota_fiscal` INT(15) NOT NULL,
  `qt_gasto` INT(11) NOT NULL,
  `dt_gasto` DATE NOT NULL,
  `total_compra` DECIMAL(18,2) NOT NULL,
  `dt_pagamento` DATE NOT NULL,
  `st_pagamento` TINYINT(1) NOT NULL,
  `id_tp_gasto` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_gastos`),
  INDEX `fk_TB_GASTO_TB_TIPO_GASTO1_idx` (`id_tp_gasto` ASC),
  INDEX `fk_TB_GASTO_TB_USUARIO1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_TB_GASTO_TB_TIPO_GASTO1`
    FOREIGN KEY (`id_tp_gasto`)
    REFERENCES `sisrec`.`TB_TIPO_GASTO` (`id_tp_gasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_GASTO_TB_USUARIO1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sisrec`.`TB_USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
